export type ModuleId = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;

export type VitalState = {
  heartRate: number;
  systolic: number;
  diastolic: number;
  spo2: number;
  respiratoryRate: number;
  temperature: number;
  rhythm: "sinus" | "stemi" | "vf" | "rosc";
};

export type PatientPhase =
  | "assessment"
  | "revealing"
  | "reasoning"
  | "diagnostics"
  | "treatment"
  | "vf"
  | "rosc"
  | "team"
  | "integrated";

export type SimulationAction = {
  id: string;
  label: string;
  shortLabel: string;
  group: string;
  description: string;
  rationale: string;
  feedback: string;
  timeCost: number;
  financialCost?: number;
  diagnosticValue?: "yüksek" | "orta" | "düşük";
  score: number;
  required?: boolean;
  critical?: boolean;
  safety: "positive" | "neutral" | "warning" | "critical";
  requires?: string[];
  phase?: PatientPhase;
  transitionTo?: PatientPhase;
  vitalDelta?: Partial<Omit<VitalState, "rhythm">>;
  rhythm?: VitalState["rhythm"];
  reveal?: string;
  skill: string;
};

export type SimulationModule = {
  id: ModuleId;
  code: string;
  title: string;
  subtitle: string;
  minimumScore: number;
  scenarioTarget: number;
  duration: string;
  level: string;
  objective: string;
  skills: string[];
  horizontalIntegration: string[];
  verticalIntegration: string[];
  initialPhase: PatientPhase;
  initialVitals: VitalState;
  requiresRationale?: boolean;
  briefing: string;
  patientStatement: string;
  actions: SimulationAction[];
  expertApproach: string;
  nextFocus: string;
};

const baseVitals: VitalState = {
  heartRate: 108,
  systolic: 94,
  diastolic: 62,
  spo2: 89,
  respiratoryRate: 24,
  temperature: 36.7,
  rhythm: "sinus",
};

export const patientProfile = {
  initials: "MK",
  age: 58,
  sex: "Erkek",
  location: "Acil Servis — Resüsitasyon Alanı 2",
  complaint: "45 dakikadır devam eden baskı tarzında göğüs ağrısı",
  appearance: "Soluk, terli, huzursuz; cümleleri kısa ve nefesi hızlı",
  history: "Hipertansiyon, sigara kullanımı ve ailede erken yaş koroner arter hastalığı",
};

export const medicalSimulationModules: SimulationModule[] = [
  {
    id: 1,
    code: "01",
    title: "Sanal Hasta",
    subtitle: "Temel hasta karşılaşması",
    minimumScore: 70,
    scenarioTarget: 3,
    duration: "20–25 dk",
    level: "Başlangıç",
    objective:
      "Hasta güvenliğini koruyarak ilk karşılaşmayı yürütmek, yapılandırılmış anamnez almak ve kritik klinik veriyi toplamak.",
    skills: ["İlk karşılaşma", "OPQRST", "ABCDE gözlemi", "Odaklı muayene", "Hasta iletişimi"],
    horizontalIntegration: ["Acil Tıp", "Kardiyoloji", "İletişim Becerileri", "Profesyonellik"],
    verticalIntegration: ["Temel yaşam bulguları", "Klinik beceri laboratuvarı", "Acil servis uygulaması"],
    initialPhase: "assessment",
    initialVitals: baseVitals,
    briefing:
      "58 yaşında erkek hasta göğüs ağrısı, terleme ve nefes darlığı ile getirildi. İlk dakikalarda güvenli ve sistematik bir hasta karşılaşması yürüt.",
    patientStatement: "Göğsümün ortasında çok ağır bir baskı var… sol koluma doğru gidiyor.",
    expertApproach:
      "Kimlik ve iletişim güvenliği sağlandıktan sonra ilk bakı–ABCDE, eşzamanlı vital değerlendirme ve odaklı OPQRST/SAMPLE anamnezi gecikmeden tamamlanır. Hem veri toplama hem de hastanın kaygısını azaltma birlikte yürütülür.",
    nextFocus: "Bir sonraki denemede kritik veriyi daha erken toplarken hastayla göz teması ve açıklayıcı iletişimi koru.",
    actions: [
      {
        id: "introduce-consent",
        label: "Kendini tanıt, kimliği doğrula ve görüşme izni al",
        shortLabel: "Güvenli başlangıç",
        group: "İletişim",
        description: "Hasta kimliği, rol açıklaması ve kısa görüşme izni.",
        rationale: "Güvenli ve profesyonel hasta karşılaşmasının temelidir.",
        feedback: "Hasta iş birliği arttı; kaygısı kısmen azaldı.",
        timeCost: 1,
        score: 8,
        required: true,
        safety: "positive",
        skill: "Hasta iletişimi",
        reveal: "Hasta adını doğruladı ve ağrısının çok şiddetli olduğunu söyledi.",
      },
      {
        id: "first-look-abcde",
        label: "İlk bakı ve ABCDE gözlemini başlat",
        shortLabel: "ABCDE",
        group: "Gözlem",
        description: "Hava yolu, solunum, dolaşım, bilinç ve genel maruziyet değerlendirmesi.",
        rationale: "Kritik tehditleri anamnezden önce veya eşzamanlı tanımayı sağlar.",
        feedback: "Solukluk, terleme, takipne ve dolaşım riski fark edildi.",
        timeCost: 2,
        score: 15,
        required: true,
        critical: true,
        safety: "positive",
        skill: "ABCDE",
        reveal: "Hava yolu açık; solunum hızlı, perifer soğuk ve nabız taşikardik.",
      },
      {
        id: "vital-monitor",
        label: "Vital bulguları ölç ve monitörizasyonu başlat",
        shortLabel: "Vital + monitör",
        group: "Gözlem",
        description: "Kan basıncı, SpO₂, solunum, nabız ve ritim takibi.",
        rationale: "Hem başlangıç şiddetini hem de sonraki yanıtı görünür kılar.",
        feedback: "Hipotansiyon ve hipoksemi görünür hâle geldi.",
        timeCost: 2,
        score: 14,
        required: true,
        critical: true,
        safety: "positive",
        skill: "Vital değerlendirme",
        reveal: "TA 94/62 mmHg, SpO₂ %89, nabız 108/dk, solunum 24/dk.",
      },
      {
        id: "opqrst",
        label: "Ağrıyı OPQRST ile sorgula",
        shortLabel: "OPQRST",
        group: "Anamnez",
        description: "Başlangıç, tetikleyici, nitelik, yayılım, şiddet ve süre.",
        rationale: "Akut koroner sendrom olasılığını yapılandırılmış biçimde belirginleştirir.",
        feedback: "Tipik iskemik ağrı özellikleri ortaya çıktı.",
        timeCost: 3,
        score: 14,
        required: true,
        safety: "positive",
        skill: "Odaklı anamnez",
        reveal: "Ağrı eforla başladı, baskı tarzında, sol kola yayılıyor ve 9/10 şiddetinde.",
      },
      {
        id: "sample-history",
        label: "Alerji, ilaç, özgeçmiş ve risk faktörlerini sorgula",
        shortLabel: "SAMPLE",
        group: "Anamnez",
        description: "Alerji, düzenli ilaç, hastalıklar, son oral alım ve olay öyküsü.",
        rationale: "Tedavi güvenliği ve kardiyovasküler risk değerlendirmesi için gereklidir.",
        feedback: "Hipertansiyon, sigara ve aspirin alerjisi olmadığı öğrenildi.",
        timeCost: 3,
        score: 10,
        required: true,
        safety: "positive",
        skill: "İlaç güvenliği",
        reveal: "Aspirin alerjisi yok; antihipertansifini düzensiz kullanıyor ve günde bir paket sigara içiyor.",
      },
      {
        id: "focused-exam",
        label: "Odaklı kardiyopulmoner fizik muayene yap",
        shortLabel: "Odaklı muayene",
        group: "Muayene",
        description: "Kalp, akciğer, periferik perfüzyon ve eşlik eden bulgular.",
        rationale: "Şok, kalp yetersizliği ve alternatif acilleri değerlendirmeye yardım eder.",
        feedback: "Akciğer sesleri açık, periferik perfüzyon zayıf bulundu.",
        timeCost: 4,
        score: 10,
        required: true,
        safety: "positive",
        skill: "Fizik muayene",
        reveal: "Ral yok; kapiller dolum uzamış, perifer soğuk ve terli.",
      },
      {
        id: "long-social-history",
        label: "Acil tehditleri değerlendirmeden ayrıntılı sosyal öyküye geç",
        shortLabel: "Uzun sosyal öykü",
        group: "Anamnez",
        description: "Kritik ilk değerlendirmeyi geciktiren uzun sorgulama.",
        rationale: "Bazı veriler değerlidir ancak zamanlama hasta güvenliğine göre önceliklendirilmelidir.",
        feedback: "Kritik değerlendirme gecikti; hasta daha huzursuz oldu.",
        timeCost: 6,
        score: -12,
        safety: "warning",
        skill: "Önceliklendirme",
        vitalDelta: { systolic: -4, spo2: -1 },
      },
      {
        id: "send-waiting-room",
        label: "Hastayı tetkik sırası için monitörsüz bekleme alanına yönlendir",
        shortLabel: "Monitörsüz beklet",
        group: "Hasta güvenliği",
        description: "Yüksek riskli hastayı gözlem dışına çıkarır.",
        rationale: "Hipotansiyon ve hipoksemi bulunan göğüs ağrılı hastada kabul edilemez risk oluşturur.",
        feedback: "Hasta güvenliği kritik biçimde tehlikeye girdi.",
        timeCost: 8,
        score: -30,
        critical: true,
        safety: "critical",
        skill: "Hasta güvenliği",
        vitalDelta: { systolic: -12, spo2: -4, heartRate: 10 },
      },
    ],
  },
  {
    id: 2,
    code: "02",
    title: "Olguya Dayalı Öğrenme",
    subtitle: "Aşamalı bilgi açılımı",
    minimumScore: 72,
    scenarioTarget: 3,
    duration: "25–30 dk",
    level: "Başlangıç+",
    objective:
      "Olgu bilgilerini aşamalı biçimde açmak, her yeni verinin klinik anlamını gerekçelendirmek ve erken kapanmadan kaçınmak.",
    skills: ["Aşamalı olgu çözümü", "Gerekçelendirme", "Bilgi talebi", "Erken kapanmayı önleme"],
    horizontalIntegration: ["Kardiyoloji", "Acil Tıp", "Fizyopatoloji", "Kanıta Dayalı Tıp"],
    verticalIntegration: ["Semptom–mekanizma", "Olgu tartışması", "Klinik karar"],
    initialPhase: "revealing",
    initialVitals: baseVitals,
    requiresRationale: true,
    briefing:
      "Olgunun tüm bilgileri başlangıçta görünmez. Bir sonraki bilgiyi neden istediğini düşünerek aç ve her kararın gerekçesini kaydet.",
    patientStatement: "Önce neyi bilmeniz gerektiğini siz seçin doktor…",
    expertApproach:
      "Önce yaşamı tehdit eden durumları ayıracak yüksek getirili bilgi talep edilir. Her yeni veri, problem temsilini güncellemek için kullanılır; tek bulguya dayanarak tanısal kapanma yapılmaz.",
    nextFocus: "Bilgiyi yalnız toplama; her yeni bulgunun olasılıkları nasıl değiştirdiğini açık bir cümleyle ifade et.",
    actions: [
      {
        id: "reveal-complaint",
        label: "Başvuru yakınmasını ve zaman çizgisini aç",
        shortLabel: "Yakınma",
        group: "Olgu açılımı",
        description: "Başlangıç zamanı, süre ve baskın semptom.",
        rationale: "Acil öncelik ve hastalık penceresini belirler.",
        feedback: "45 dakikalık sürekli göğüs ağrısı açıldı.",
        timeCost: 1,
        score: 12,
        required: true,
        safety: "positive",
        skill: "Olgu yapılandırma",
        reveal: "Ağrı 45 dakika önce efor sırasında başladı ve dinlenmeyle geçmedi.",
      },
      {
        id: "reveal-history",
        label: "Odaklı anamnez paketini aç",
        shortLabel: "Anamnez",
        group: "Olgu açılımı",
        description: "Ağrı özellikleri, eşlik eden semptomlar ve riskler.",
        rationale: "İskemik örüntüyü ve alternatif acilleri karşılaştırır.",
        feedback: "Yayılım, terleme ve bulantı bilgileri açıldı.",
        timeCost: 2,
        score: 13,
        required: true,
        requires: ["reveal-complaint"],
        safety: "positive",
        skill: "Bilgi sıralama",
        reveal: "Baskı tarzındaki ağrı sol kola yayılıyor; soğuk terleme ve bulantı eşlik ediyor.",
      },
      {
        id: "reveal-vitals",
        label: "Vital bulguları ve eğilimi aç",
        shortLabel: "Vital eğilim",
        group: "Olgu açılımı",
        description: "Tek ölçüm yerine başlangıç eğilimi.",
        rationale: "Hem şiddeti hem de acil müdahale ihtiyacını belirler.",
        feedback: "Hipotansiyon ve hipoksemi görünür oldu.",
        timeCost: 1,
        score: 15,
        required: true,
        critical: true,
        requires: ["reveal-complaint"],
        safety: "positive",
        skill: "Risk sınıflama",
        reveal: "TA 94/62, SpO₂ %89, nabız 108; son beş dakikada basınç düşme eğiliminde.",
      },
      {
        id: "reveal-exam",
        label: "Odaklı fizik muayene bulgularını aç",
        shortLabel: "Muayene",
        group: "Olgu açılımı",
        description: "Perfüzyon, akciğer ve kardiyak bulgular.",
        rationale: "Şok fenotipi ve eşlik eden kalp yetersizliğini değerlendirir.",
        feedback: "Soğuk perifer ve uzamış kapiller dolum açıldı.",
        timeCost: 2,
        score: 12,
        required: true,
        requires: ["reveal-vitals"],
        safety: "positive",
        skill: "Muayene yorumlama",
        reveal: "Perifer soğuk, kapiller dolum 4 saniye; akciğerlerde ral yok.",
      },
      {
        id: "reveal-ecg",
        label: "12 derivasyonlu EKG bilgisini aç",
        shortLabel: "EKG",
        group: "Kritik veri",
        description: "Semptom ve dolaşım bulgularından sonra yüksek değerli tanısal veri.",
        rationale: "STEMI olasılığını hızla doğrular ve reperfüzyon yolunu açar.",
        feedback: "V1–V4 derivasyonlarında ST yükselmesi görüldü.",
        timeCost: 3,
        score: 20,
        required: true,
        critical: true,
        requires: ["reveal-history", "reveal-vitals"],
        safety: "positive",
        skill: "Kritik veri seçimi",
        rhythm: "stemi",
        reveal: "V1–V4'te belirgin ST elevasyonu ve karşılıklı inferior değişiklikler var.",
      },
      {
        id: "declare-anxiety",
        label: "Vital ve EKG verisi olmadan olguyu anksiyete atağı olarak kapat",
        shortLabel: "Erken kapanma",
        group: "Bilişsel hata",
        description: "Tek açıklamaya erken bağlanma.",
        rationale: "Yüksek riskli göğüs ağrısında doğrulayıcı veri olmadan tanısal kapanma tehlikelidir.",
        feedback: "Erken kapanma, kritik kardiyak olguyu geciktirdi.",
        timeCost: 5,
        score: -28,
        safety: "critical",
        skill: "Bilişsel hata farkındalığı",
        vitalDelta: { systolic: -8, spo2: -2 },
      },
      {
        id: "reveal-all-at-once",
        label: "Tüm olgu paketini gerekçe belirtmeden tek seferde aç",
        shortLabel: "Toplu açılım",
        group: "Öğrenme süreci",
        description: "Bilgi taleplerinin klinik amacını görünmez kılar.",
        rationale: "Olguya dayalı öğrenmede seçim ve gerekçe, yalnız sonuca ulaşmak kadar önemlidir.",
        feedback: "Doğru verilere ulaşıldı ancak düşünme izi oluşmadı.",
        timeCost: 1,
        score: -8,
        safety: "neutral",
        skill: "Gerekçelendirme",
      },
    ],
  },
  {
    id: 3,
    code: "03",
    title: "Klinik Akıl Yürütme",
    subtitle: "Düşünme izini görünür kıl",
    minimumScore: 75,
    scenarioTarget: 4,
    duration: "30–35 dk",
    level: "Orta",
    objective:
      "Problem temsili oluşturmak, bulguları ağırlıklandırmak, ayırıcı tanıyı önceliklendirmek ve yeni bilgiyle hipotezleri güncellemek.",
    skills: ["Problem temsili", "Ayırıcı tanı", "Kırmızı bayrak", "Olasılık güncelleme", "Belirsizlik"],
    horizontalIntegration: ["Kardiyoloji", "Acil Tıp", "Radyoloji", "Klinik Epidemiyoloji"],
    verticalIntegration: ["Fizyopatoloji", "Semiyoloji", "Klinik karar", "Uzmanlık düzeyi muhakeme"],
    initialPhase: "reasoning",
    initialVitals: { ...baseVitals, rhythm: "stemi" },
    requiresRationale: true,
    briefing:
      "Toplanan verileri tek cümlelik problem temsiline dönüştür; ayırıcı tanını kur, kırmızı bayrakları işaretle ve EKG sonrası olasılıklarını güncelle.",
    patientStatement: "Ağrı hâlâ geçmedi… daha kötü hissediyorum.",
    expertApproach:
      "Yaş, risk, ağrı örüntüsü, otonom semptomlar ve hemodinamik etkilenme kısa problem temsiline alınır. Ölümcül alternatifler açık tutulurken EKG sonrası STEMI en yüksek önceliğe yükseltilir ve belirsizlik düzeyi yeniden ifade edilir.",
    nextFocus: "Ayırıcı tanıyı uzun bir liste olarak değil; olasılık, tehlike ve eylem gereksinimine göre sıralı tut.",
    actions: [
      {
        id: "problem-representation",
        label: "Tek cümlelik problem temsili oluştur",
        shortLabel: "Problem temsili",
        group: "Sentez",
        description: "Yaş, zaman, sendrom, risk ve şiddeti yoğunlaştır.",
        rationale: "Dağınık veriyi eyleme dönük klinik probleme çevirir.",
        feedback: "Kritik özellikleri içeren kısa bir problem temsili oluşturuldu.",
        timeCost: 2,
        score: 15,
        required: true,
        safety: "positive",
        skill: "Problem temsili",
        reveal: "58 yaş, kardiyovasküler riskli, 45 dakikalık tipik iskemik ağrı ve hemodinamik etkilenme.",
      },
      {
        id: "salient-features",
        label: "Ayırt edici bulguları seç ve ağırlıklandır",
        shortLabel: "Bulguları ağırlıklandır",
        group: "Sentez",
        description: "Yayılım, terleme, hipotansiyon, hipoksemi ve EKG.",
        rationale: "Her bulgunun tanısal ve prognostik ağırlığı aynı değildir.",
        feedback: "Yüksek ağırlıklı bulgular ön plana alındı.",
        timeCost: 2,
        score: 14,
        required: true,
        requires: ["problem-representation"],
        safety: "positive",
        skill: "İpucu ağırlıklandırma",
      },
      {
        id: "differential",
        label: "Ölümcül alternatifleri içeren ayırıcı tanı oluştur",
        shortLabel: "Ayırıcı tanı",
        group: "Hipotez",
        description: "AKS, aort diseksiyonu, pulmoner emboli, pnömotoraks ve diğerleri.",
        rationale: "En olası tanı ile en tehlikeli alternatifleri birlikte yönetir.",
        feedback: "Ayırıcı tanı olasılık ve tehlike ekseninde kuruldu.",
        timeCost: 3,
        score: 14,
        required: true,
        requires: ["salient-features"],
        safety: "positive",
        skill: "Hipotez oluşturma",
      },
      {
        id: "red-flags",
        label: "Kırmızı bayrakları işaretle",
        shortLabel: "Kırmızı bayraklar",
        group: "Risk",
        description: "Hipotansiyon, devam eden ağrı, hipoksemi ve perfüzyon bozukluğu.",
        rationale: "Tanı kesinleşmeden de acil eylem gerektiren riskleri belirler.",
        feedback: "Hemodinamik instabilite ve devam eden iskemi tanındı.",
        timeCost: 1,
        score: 16,
        required: true,
        critical: true,
        safety: "positive",
        skill: "Risk tanıma",
      },
      {
        id: "prioritize-stemi",
        label: "EKG sonrası STEMI olasılığını en yüksek önceliğe taşı",
        shortLabel: "STEMI önceliği",
        group: "Olasılık güncelleme",
        description: "Yeni EKG verisiyle hipotez sıralamasını değiştir.",
        rationale: "Yeni kanıtın karar üzerindeki etkisini görünür kılar.",
        feedback: "STEMI en olası ve en zaman kritik tanı olarak önceliklendirildi.",
        timeCost: 1,
        score: 20,
        required: true,
        critical: true,
        requires: ["differential", "red-flags"],
        safety: "positive",
        skill: "Bayesyen güncelleme",
        reveal: "EKG, anterior STEMI olasılığını belirgin biçimde artırdı.",
      },
      {
        id: "ignore-hypotension",
        label: "Tanı belli olduğu için hipotansiyonu ayrı bir problem olarak ele alma",
        shortLabel: "Şoku göz ardı et",
        group: "Bilişsel hata",
        description: "Tanı etiketinin fizyolojik riski gölgelemesi.",
        rationale: "Hemodinamik bozulma, tanıdan bağımsız acil yönetim gerektirir.",
        feedback: "Hasta güvenliğini etkileyen dolaşım sorunu problem listesinden düştü.",
        timeCost: 3,
        score: -22,
        safety: "critical",
        skill: "Problem listesi",
        vitalDelta: { systolic: -8 },
      },
      {
        id: "certainty-100",
        label: "Alternatifleri kapat ve tanısal kesinliği %100 ilan et",
        shortLabel: "Aşırı kesinlik",
        group: "Belirsizlik",
        description: "Kalan belirsizliği yok sayar.",
        rationale: "Güçlü kanıt olsa bile alternatif riskler ve komplikasyonlar izlenmeye devam eder.",
        feedback: "Tanısal aşırı güven, yeniden değerlendirme açıklığını azalttı.",
        timeCost: 1,
        score: -10,
        safety: "warning",
        skill: "Belirsizlik yönetimi",
      },
    ],
  },
  {
    id: 4,
    code: "04",
    title: "Tanı ve Tetkik",
    subtitle: "Değer, maliyet ve zaman",
    minimumScore: 76,
    scenarioTarget: 4,
    duration: "25–30 dk",
    level: "Orta",
    objective:
      "Tanısal değeri yüksek tetkikleri zaman ve maliyet bilinciyle seçmek; gereksiz testlerin hasta sonucuna etkisini değerlendirmek.",
    skills: ["Tetkik gerekçesi", "Tanısal değer", "Maliyet farkındalığı", "Zaman yönetimi"],
    horizontalIntegration: ["Kardiyoloji", "Laboratuvar Tıbbı", "Radyoloji", "Sağlık Ekonomisi"],
    verticalIntegration: ["Temel test bilgisi", "Klinik endikasyon", "Kaynak yönetimi"],
    initialPhase: "diagnostics",
    initialVitals: { ...baseVitals, rhythm: "stemi" },
    briefing:
      "Her tetkik zaman ve maliyet tüketir. Reperfüzyon kararını geciktirmeden yüksek değerli testleri seç; gereksiz testlerin puana yansıdığını unutma.",
    patientStatement: "Ne kadar daha test yapılacak? Ağrım devam ediyor.",
    expertApproach:
      "12 derivasyonlu EKG ilk dakikalarda elde edilir. Troponin ve temel laboratuvarlar alınır ancak STEMI reperfüzyonu sonuç beklenerek geciktirilmez. Yatak başı ultrason, hemodinamik değerlendirmede hedefli kullanılabilir.",
    nextFocus: "Her test için şu soruyu sor: Bu sonuç şimdi vereceğim kararı değiştirecek mi ve beklemek hastaya neye mal olacak?",
    actions: [
      {
        id: "test-ecg",
        label: "12 derivasyonlu EKG — hemen",
        shortLabel: "EKG",
        group: "Kardiyak",
        description: "3 dakika · düşük maliyet · çok yüksek tanısal değer",
        rationale: "STEMI tanısı ve reperfüzyon yolunun temel zaman kritik testidir.",
        feedback: "Anterior STEMI bulguları doğrulandı.",
        timeCost: 3,
        financialCost: 120,
        diagnosticValue: "yüksek",
        score: 24,
        required: true,
        critical: true,
        safety: "positive",
        skill: "Yüksek değerli tetkik",
        rhythm: "stemi",
        reveal: "V1–V4'te ST elevasyonu.",
      },
      {
        id: "test-troponin",
        label: "Troponin ve temel biyokimya — reperfüzyonu bekletmeden",
        shortLabel: "Troponin",
        group: "Laboratuvar",
        description: "25 dakika · orta maliyet · yüksek tamamlayıcı değer",
        rationale: "Tanı ve risk için değerlidir ancak belirgin STEMI'de reperfüzyon kararını geciktirmemelidir.",
        feedback: "Kan alındı; sonuç beklenmeden zaman kritik yol sürdürüldü.",
        timeCost: 2,
        financialCost: 650,
        diagnosticValue: "yüksek",
        score: 14,
        required: true,
        safety: "positive",
        skill: "Test zamanlaması",
      },
      {
        id: "test-basic-labs",
        label: "Hemogram, elektrolit, kreatinin ve glukoz",
        shortLabel: "Temel laboratuvar",
        group: "Laboratuvar",
        description: "20 dakika · orta maliyet · tedavi güvenliği için orta-yüksek değer",
        rationale: "Eşlik eden riskleri, ilaç ve girişim güvenliğini destekler.",
        feedback: "Tedavi güvenliği için gerekli temel laboratuvar paketi istendi.",
        timeCost: 2,
        financialCost: 900,
        diagnosticValue: "orta",
        score: 10,
        required: true,
        safety: "positive",
        skill: "Tedavi güvenliği",
      },
      {
        id: "test-pocus",
        label: "Hedefli yatak başı kardiyak ultrason",
        shortLabel: "POCUS",
        group: "Görüntüleme",
        description: "5 dakika · düşük-orta maliyet · hemodinamik değer",
        rationale: "Pompa fonksiyonu, komplikasyon ve alternatif şok nedenlerini hedefli değerlendirir.",
        feedback: "Anterior duvar hareket kusuru ve azalmış sol ventrikül fonksiyonu görüldü.",
        timeCost: 5,
        financialCost: 750,
        diagnosticValue: "yüksek",
        score: 15,
        safety: "positive",
        skill: "Yatak başı görüntüleme",
        reveal: "Anterior hipokinezi; belirgin perikardiyal efüzyon yok.",
      },
      {
        id: "test-cxr",
        label: "Taşınabilir akciğer grafisi — klinik yol gecikmeden",
        shortLabel: "Akciğer grafisi",
        group: "Görüntüleme",
        description: "10 dakika · orta maliyet · alternatifler için sınırlı değer",
        rationale: "Seçilmiş hastada yardımcı olabilir; kateter laboratuvarı aktivasyonunu geciktirmemelidir.",
        feedback: "Grafi alındı; belirgin pnömotoraks veya ödem görülmedi.",
        timeCost: 4,
        financialCost: 500,
        diagnosticValue: "orta",
        score: 4,
        safety: "neutral",
        skill: "Seçici görüntüleme",
      },
      {
        id: "test-ctpa",
        label: "STEMI EKG'sine rağmen BT pulmoner anjiyografi iste",
        shortLabel: "BT pulmoner anjiyo",
        group: "Görüntüleme",
        description: "35 dakika · yüksek maliyet · mevcut tabloda düşük marjinal değer",
        rationale: "Pulmoner emboli ayırıcıda olsa da mevcut güçlü STEMI kanıtı ve instabilite nedeniyle öncelikli değildir.",
        feedback: "Reperfüzyon gecikti ve hasta dolaşımı kötüleşti.",
        timeCost: 35,
        financialCost: 5200,
        diagnosticValue: "düşük",
        score: -25,
        safety: "critical",
        skill: "Gereksiz tetkik",
        vitalDelta: { systolic: -15, spo2: -3, heartRate: 12 },
      },
      {
        id: "test-mri",
        label: "Acil kardiyak MR planla",
        shortLabel: "Kardiyak MR",
        group: "Görüntüleme",
        description: "60+ dakika · çok yüksek maliyet · akut karar için uygunsuz",
        rationale: "Akut instabil STEMI'nin ilk yönetiminde zaman ve erişim açısından uygun değildir.",
        feedback: "Kritik zaman kaybı oluştu.",
        timeCost: 60,
        financialCost: 8500,
        diagnosticValue: "düşük",
        score: -30,
        safety: "critical",
        skill: "Kaynak yönetimi",
        vitalDelta: { systolic: -20, spo2: -5 },
      },
      {
        id: "wait-troponin",
        label: "Kateter laboratuvarı kararından önce troponin sonucunu bekle",
        shortLabel: "Sonucu bekle",
        group: "Zamanlama",
        description: "25 dakikalık karar gecikmesi.",
        rationale: "Tanısal EKG bulunan STEMI'de biyobelirteç sonucu reperfüzyon aktivasyonunu geciktirmemelidir.",
        feedback: "Kapı-balon süresini uzatan kritik gecikme oluştu.",
        timeCost: 25,
        score: -26,
        safety: "critical",
        skill: "Zaman kritik karar",
        vitalDelta: { systolic: -10, spo2: -2 },
      },
    ],
  },
  {
    id: 5,
    code: "05",
    title: "Tedavi ve Müdahale",
    subtitle: "Karar–yanıt döngüsü",
    minimumScore: 78,
    scenarioTarget: 4,
    duration: "30 dk",
    level: "Orta+",
    objective:
      "Tedaviyi endikasyon, kontrendikasyon, doz, yol ve zamanlama ile seçmek; hastanın dinamik yanıtını yeniden değerlendirmek.",
    skills: ["İlaç güvenliği", "Oksijen", "Monitörizasyon", "Reperfüzyon aktivasyonu", "Yeniden değerlendirme"],
    horizontalIntegration: ["Kardiyoloji", "Acil Tıp", "Farmakoloji", "Hemşirelik Uygulamaları"],
    verticalIntegration: ["Farmakodinami", "Klinik endikasyon", "Akut bakım", "Komplikasyon yönetimi"],
    initialPhase: "treatment",
    initialVitals: { ...baseVitals, rhythm: "stemi" },
    briefing:
      "Anterior STEMI, hipotansiyon ve SpO₂ %89. Müdahaleleri doz, yol ve zamanlama bilinciyle seç; her işlemden sonra hastanın yanıtını izle.",
    patientStatement: "Nefesim daralıyor… ağrı hâlâ dokuz üzerinden dokuz.",
    expertApproach:
      "Monitörizasyon ve damar yolu eşzamanlı kurulur. Hipoksemi nedeniyle kontrollü oksijen, kontrendikasyon yoksa çiğnetilerek aspirin ve erken kateter laboratuvarı aktivasyonu uygulanır. Hipotansiyon nedeniyle nitrat verilmez; her müdahale sonrası vital yanıt yeniden değerlendirilir.",
    nextFocus: "Doğru tedaviyi seçmek kadar kontrendikasyonu fark etmek ve yanıtı yeniden ölçmek de yeterliliğin parçasıdır.",
    actions: [
      {
        id: "treat-monitor-iv",
        label: "Sürekli monitörizasyon ve iki damar yolu kur",
        shortLabel: "Monitör + IV",
        group: "Destek",
        description: "Ritim takibi ve güvenli ilaç/girişim erişimi.",
        rationale: "İnstabil STEMI'de ani ritim ve dolaşım değişikliklerini yakalar.",
        feedback: "Hasta sürekli izleme ve müdahale erişimine alındı.",
        timeCost: 3,
        score: 16,
        required: true,
        critical: true,
        safety: "positive",
        skill: "Monitörizasyon",
      },
      {
        id: "treat-oxygen",
        label: "Hipoksemi için kontrollü oksijen başla",
        shortLabel: "Oksijen",
        group: "Destek",
        description: "SpO₂ hedefli oksijen uygulaması.",
        rationale: "SpO₂ %89 olduğu için hipoksemiyi düzeltmek endikedir.",
        feedback: "SpO₂ yükseldi ve solunum sıkıntısı azaldı.",
        timeCost: 2,
        score: 14,
        required: true,
        safety: "positive",
        skill: "Oksijen tedavisi",
        vitalDelta: { spo2: 6, respiratoryRate: -3 },
      },
      {
        id: "treat-aspirin",
        label: "Alerji yoksa 300 mg aspirini çiğnet",
        shortLabel: "Aspirin 300 mg",
        group: "İlaç",
        description: "Doğru doz ve hızlı emilim yolu.",
        rationale: "Akut koroner trombozda erken antiplatelet etki sağlar.",
        feedback: "Aspirin güvenli doz ve yolla uygulandı.",
        timeCost: 1,
        score: 18,
        required: true,
        critical: true,
        safety: "positive",
        skill: "İlaç güvenliği",
      },
      {
        id: "treat-cath-lab",
        label: "Primer PKG yolu için kateter laboratuvarını aktive et",
        shortLabel: "Kateter aktivasyonu",
        group: "Reperfüzyon",
        description: "Zaman kritik kesin tedavi yolunu başlatır.",
        rationale: "STEMI'de gecikmeden reperfüzyon planı gerekir.",
        feedback: "Kateter ekibi aktive edildi; transfer hazırlığı başladı.",
        timeCost: 2,
        score: 25,
        required: true,
        critical: true,
        safety: "positive",
        skill: "Reperfüzyon",
        vitalDelta: { heartRate: -4 },
      },
      {
        id: "treat-cautious-fluid",
        label: "Hipotansiyon için küçük hacimli sıvı bolusu ver ve yeniden değerlendir",
        shortLabel: "Kontrollü sıvı",
        group: "Dolaşım",
        description: "Akciğer bulguları açıkken küçük bolus ve yakın yeniden değerlendirme.",
        rationale: "Dolaşım desteği hedefli ve aşırı yüklenmeden uygulanmalıdır.",
        feedback: "Kan basıncı sınırlı yükseldi; akciğer bulguları değişmedi.",
        timeCost: 4,
        score: 10,
        safety: "positive",
        skill: "Hemodinamik destek",
        vitalDelta: { systolic: 8, diastolic: 4 },
      },
      {
        id: "treat-reassess",
        label: "Müdahaleler sonrası ağrı, vital ve perfüzyonu yeniden değerlendir",
        shortLabel: "Yeniden değerlendir",
        group: "Değerlendirme",
        description: "Tedavi etkisi ve olası kötüleşme kontrolü.",
        rationale: "Karar–uygulama–sonuç döngüsünü tamamlar.",
        feedback: "Hasta yanıtı kaydedildi; kötüleşme riski görünür kaldı.",
        timeCost: 2,
        score: 12,
        required: true,
        safety: "positive",
        skill: "Yeniden değerlendirme",
      },
      {
        id: "treat-nitrate",
        label: "TA 94/62 iken dil altı nitrogliserin ver",
        shortLabel: "Nitrat",
        group: "İlaç",
        description: "Hipotansiyonda vazodilatör uygulama.",
        rationale: "Düşük kan basıncında nitrat ciddi hipotansiyonu artırabilir.",
        feedback: "Kan basıncı kritik düzeyde düştü ve hasta bilinç bulanıklığı yaşadı.",
        timeCost: 1,
        score: -35,
        critical: true,
        safety: "critical",
        skill: "Kontrendikasyon",
        vitalDelta: { systolic: -25, diastolic: -14, heartRate: 14 },
      },
      {
        id: "treat-routine-oxygen-high",
        label: "Hedef gözetmeden yüksek akımlı oksijeni sürekli sürdür",
        shortLabel: "Kontrolsüz oksijen",
        group: "Destek",
        description: "Yanıt izlenmeden gereksiz yüksek oksijen.",
        rationale: "Oksijen tedavisi hipoksemi ve hedef satürasyona göre titrasyon gerektirir.",
        feedback: "Tedavi hedefi ve yeniden değerlendirme göz ardı edildi.",
        timeCost: 2,
        score: -6,
        safety: "warning",
        skill: "Tedavi titrasyonu",
        vitalDelta: { spo2: 8 },
      },
    ],
  },
  {
    id: 6,
    code: "06",
    title: "Acil Durum Simülasyonları",
    subtitle: "Zaman kritik resüsitasyon",
    minimumScore: 80,
    scenarioTarget: 5,
    duration: "15–20 dk",
    level: "İleri",
    objective:
      "Şoklanabilir ritmi hızla tanımak, yüksek kaliteli CPR ve erken defibrilasyonu gecikmesiz uygulamak.",
    skills: ["Ritim tanıma", "CPR", "Defibrilasyon", "Zaman yönetimi", "ROSC sonrası bakım"],
    horizontalIntegration: ["Acil Tıp", "Kardiyoloji", "Anesteziyoloji", "Yoğun Bakım"],
    verticalIntegration: ["Temel yaşam desteği", "İleri yaşam desteği", "Klinik liderlik"],
    initialPhase: "vf",
    initialVitals: {
      heartRate: 0,
      systolic: 0,
      diastolic: 0,
      spo2: 72,
      respiratoryRate: 0,
      temperature: 36.6,
      rhythm: "vf",
    },
    briefing:
      "Hasta aniden yanıtsızlaştı. Monitörde ventriküler fibrilasyon var. Her işlem simülasyon zamanını ilerletir; gecikme hasta sonucunu doğrudan etkiler.",
    patientStatement: "Hasta yanıtsız; normal solunum yok ve santral nabız alınmıyor.",
    expertApproach:
      "Kod çağrısı ve yüksek kaliteli CPR hemen başlatılır; defibrilatör hazır olduğunda ritim hızlıca doğrulanıp şok verilir ve kesintisiz CPR'a dönülür. İlaç ve ileri hava yolu, erken defibrilasyonu geciktirmez.",
    nextFocus: "Ekipman hazırlığını CPR ile eşzamanlı yürüt; şok öncesi ve sonrası kompresyon kesintisini minimumda tut.",
    actions: [
      {
        id: "emergency-call-code",
        label: "Kardiyak arrest çağrısı yap ve defibrilatörü getir",
        shortLabel: "Kod çağrısı",
        group: "İlk yanıt",
        description: "Ekibi ve kritik ekipmanı eşzamanlı aktive eder.",
        rationale: "Tek kişinin müdahalesinden ekip resüsitasyonuna hızlı geçiş sağlar.",
        feedback: "Resüsitasyon ekibi ve defibrilatör çağrıldı.",
        timeCost: 1,
        score: 12,
        required: true,
        safety: "positive",
        skill: "Kaynak aktivasyonu",
      },
      {
        id: "emergency-cpr",
        label: "Yüksek kaliteli göğüs kompresyonuna hemen başla",
        shortLabel: "CPR",
        group: "Resüsitasyon",
        description: "Kesintiyi azaltan etkili kompresyon.",
        rationale: "Defibrilasyona kadar koroner ve serebral perfüzyonu destekler.",
        feedback: "Kompresyon başladı; düşük düzey dolaşım sağlandı.",
        timeCost: 1,
        score: 24,
        required: true,
        critical: true,
        safety: "positive",
        skill: "Yüksek kaliteli CPR",
        vitalDelta: { spo2: 4 },
      },
      {
        id: "emergency-defib",
        label: "VF'yi doğrula, güvenliği sağla ve erken defibrilasyon uygula",
        shortLabel: "Defibrilasyon",
        group: "Resüsitasyon",
        description: "Şoklanabilir ritimde en kritik zaman bağımlı müdahale.",
        rationale: "VF'de sağkalımı belirleyen temel müdahaledir.",
        feedback: "Şok uygulandı; CPR'a hemen dönüldü.",
        timeCost: 2,
        score: 30,
        required: true,
        critical: true,
        requires: ["emergency-call-code"],
        safety: "positive",
        skill: "Defibrilasyon",
      },
      {
        id: "emergency-resume-cpr",
        label: "Şok sonrası nabız aramadan hemen CPR'a dön",
        shortLabel: "CPR'a dön",
        group: "Resüsitasyon",
        description: "Şok sonrası gereksiz kesintiyi önler.",
        rationale: "Şok sonrası ritim ve dolaşımın yerleşmesi için kompresyon sürdürülür.",
        feedback: "Kompresyon kesintisi kısa tutuldu.",
        timeCost: 1,
        score: 16,
        required: true,
        requires: ["emergency-defib"],
        safety: "positive",
        skill: "Kompresyon sürekliliği",
      },
      {
        id: "emergency-epi",
        label: "Uygun döngüde adrenalin hazırlat ve uygula",
        shortLabel: "Adrenalin",
        group: "İlaç",
        description: "Şoklanabilir ritim algoritmasında doğru zamanlama.",
        rationale: "İlaç uygulaması erken şoku geciktirmeden algoritmaya eklenir.",
        feedback: "Adrenalin doğru döngüde uygulandı.",
        timeCost: 2,
        score: 10,
        requires: ["emergency-defib", "emergency-resume-cpr"],
        safety: "positive",
        skill: "Algoritma uygulama",
      },
      {
        id: "emergency-airway",
        label: "Kompresyonu kesmeden oksijenasyon ve temel hava yolu desteği sağla",
        shortLabel: "Hava yolu",
        group: "Hava yolu",
        description: "Kompresyon önceliğini koruyan ventilasyon desteği.",
        rationale: "Hava yolu yönetimi perfüzyon müdahalelerini geciktirmemelidir.",
        feedback: "Oksijenasyon desteği kompresyonla eşzamanlı sürdürüldü.",
        timeCost: 2,
        score: 10,
        safety: "positive",
        skill: "Hava yolu",
        vitalDelta: { spo2: 7 },
      },
      {
        id: "emergency-intubate-first",
        label: "CPR ve şoktan önce uzun entübasyon denemesine başla",
        shortLabel: "Önce entübasyon",
        group: "Kritik hata",
        description: "Defibrilasyon ve kompresyonu geciktiren hava yolu girişimi.",
        rationale: "VF'de erken şok ve CPR'dan önce uzun hava yolu girişimi sağkalımı azaltır.",
        feedback: "Defibrilasyon kritik biçimde gecikti.",
        timeCost: 8,
        score: -35,
        critical: true,
        safety: "critical",
        skill: "Önceliklendirme",
      },
      {
        id: "emergency-long-pulse-check",
        label: "Her işlemden sonra uzun nabız ve ritim kontrolü yap",
        shortLabel: "Uzun kontrol",
        group: "Kritik hata",
        description: "Kompresyon kesintilerini artırır.",
        rationale: "Ritim ve nabız kontrolleri algoritmik ve kısa tutulmalıdır.",
        feedback: "Kompresyon fraksiyonu düştü.",
        timeCost: 6,
        score: -20,
        safety: "critical",
        skill: "Kompresyon kesintisi",
        vitalDelta: { spo2: -5 },
      },
    ],
  },
  {
    id: 7,
    code: "07",
    title: "Ekip Yönetimi & Klinik Liderlik",
    subtitle: "İnsan, görev ve iletişim",
    minimumScore: 82,
    scenarioTarget: 4,
    duration: "25–30 dk",
    level: "İleri",
    objective:
      "Kriz kaynağı yönetimi, görev dağılımı, kapalı döngü iletişim, SBAR ve güvenli devir teslimi uygulamak.",
    skills: ["Görev dağılımı", "Kapalı döngü", "SBAR", "Kriz kaynak yönetimi", "Devir teslim"],
    horizontalIntegration: ["Acil Tıp", "Hemşirelik", "Paramedik", "Anesteziyoloji", "Kalite ve Güvenlik"],
    verticalIntegration: ["İletişim becerileri", "Ekip çalışması", "Klinik liderlik", "Kurumsal güvenlik"],
    initialPhase: "team",
    initialVitals: {
      heartRate: 0,
      systolic: 0,
      diastolic: 0,
      spo2: 76,
      respiratoryRate: 0,
      temperature: 36.6,
      rhythm: "vf",
    },
    briefing:
      "Resüsitasyon ekibi odada: hekim, hemşire, paramedik, teknisyen ve konsültan. Hastayı yönetirken ekibin bilişsel yükünü ve iletişim güvenliğini de yönet.",
    patientStatement: "Ekip senden net görevler ve öncelik bekliyor.",
    expertApproach:
      "Lider genel resmi ve ritmi izler; roller isim ve görevle atanır, komutlar geri okunur ve tamamlanma bildirimi alınır. Kritik bilgiler SBAR ile aktarılır, ekip ortak zihinsel modelde tutulur ve devir teslim yapılandırılır.",
    nextFocus: "Komutun verildiğini değil, anlaşılıp uygulandığını doğrula; isim–görev–geri okuma–tamamlanma döngüsünü kullan.",
    actions: [
      {
        id: "team-announce-leader",
        label: "Liderliği açıkça üstlen ve ortak hedefi söyle",
        shortLabel: "Liderliği ilan et",
        group: "Liderlik",
        description: "Ekibin kimin koordinasyonunda çalışacağını netleştirir.",
        rationale: "Rol belirsizliğini ve paralel çelişkili komutları azaltır.",
        feedback: "Ekip ortak liderlik ve hedef algısına geçti.",
        timeCost: 1,
        score: 14,
        required: true,
        safety: "positive",
        skill: "Klinik liderlik",
      },
      {
        id: "team-assign-compressions",
        label: "Paramediğe kompresyon ve iki dakikada değişim görevi ver",
        shortLabel: "Kompresyon rolü",
        group: "Görev dağılımı",
        description: "Net kişi, görev ve değişim süresi.",
        rationale: "Kompresyon kalitesini ve sürekliliğini korur.",
        feedback: "Paramedik komutu geri okudu ve kompresyona başladı.",
        timeCost: 1,
        score: 14,
        required: true,
        safety: "positive",
        skill: "Görev dağılımı",
      },
      {
        id: "team-assign-defib",
        label: "Hemşireye defibrilatör hazırlama ve enerji doğrulama görevi ver",
        shortLabel: "Defibrilatör rolü",
        group: "Görev dağılımı",
        description: "Şok hazırlığını kompresyonla eşzamanlı yürütür.",
        rationale: "Liderin tüm teknik işleri kendisinin yapmasını önler.",
        feedback: "Defibrilatör hazırlandı ve enerji geri okundu.",
        timeCost: 1,
        score: 14,
        required: true,
        safety: "positive",
        skill: "Kaynak kullanımı",
      },
      {
        id: "team-closed-loop",
        label: "Tüm kritik komutlarda kapalı döngü iletişimi uygula",
        shortLabel: "Kapalı döngü",
        group: "İletişim",
        description: "İsimle hitap, geri okuma ve tamamlanma bildirimi.",
        rationale: "Komutun kaybolmasını, yanlış anlaşılmasını ve yinelenmesini azaltır.",
        feedback: "Ekip komutları geri okuyup tamamlanmayı bildirdi.",
        timeCost: 1,
        score: 20,
        required: true,
        critical: true,
        safety: "positive",
        skill: "Kapalı döngü iletişim",
      },
      {
        id: "team-sbar",
        label: "Kardiyoloji konsültanına SBAR ile kısa aktarım yap",
        shortLabel: "SBAR",
        group: "Konsültasyon",
        description: "Durum, arka plan, değerlendirme ve öneri.",
        rationale: "Zaman kritik bilgiyi yapılandırılmış ve eyleme dönük aktarır.",
        feedback: "Konsültan ortak planı teyit etti.",
        timeCost: 2,
        score: 15,
        required: true,
        safety: "positive",
        skill: "SBAR",
      },
      {
        id: "team-handoff",
        label: "ROSC sonrası yapılandırılmış devir teslim yap",
        shortLabel: "Devir teslim",
        group: "Süreklilik",
        description: "Zaman çizelgesi, müdahaleler, yanıt ve açık riskler.",
        rationale: "Bakım geçişinde kritik bilginin kaybolmasını önler.",
        feedback: "Yoğun bakım ve kateter ekibi eksiksiz bilgi aldı.",
        timeCost: 3,
        score: 14,
        required: true,
        requires: ["team-sbar"],
        safety: "positive",
        skill: "Devir teslim",
      },
      {
        id: "team-do-everything",
        label: "Tüm görevleri kendin yapmaya çalış ve ekibe belirsiz komutlar ver",
        shortLabel: "Tek kişi yönetimi",
        group: "İletişim hatası",
        description: "Mikro yönetim ve rol karmaşası.",
        rationale: "Liderin durumsal farkındalığını azaltır ve kritik işleri geciktirir.",
        feedback: "Ekip bekledi, görevler yinelendi ve şok gecikti.",
        timeCost: 6,
        score: -30,
        critical: true,
        safety: "critical",
        skill: "Kriz kaynak yönetimi",
      },
      {
        id: "team-shouting",
        label: "Komutları isim ve görev belirtmeden yüksek sesle tekrarla",
        shortLabel: "Belirsiz komut",
        group: "İletişim hatası",
        description: "Kimin sorumlu olduğunu belirsiz bırakır.",
        rationale: "Ses yüksekliği iletişim netliğinin yerine geçmez.",
        feedback: "İki kişi aynı göreve yöneldi, başka bir görev sahipsiz kaldı.",
        timeCost: 3,
        score: -18,
        safety: "warning",
        skill: "İletişim güvenliği",
      },
    ],
  },
  {
    id: 8,
    code: "08",
    title: "Entegre Klinik Simülasyon",
    subtitle: "Bağımsız karar verici",
    minimumScore: 85,
    scenarioTarget: 2,
    duration: "40–50 dk",
    level: "Final",
    objective:
      "Hasta kabulünden debriefing'e kadar önceki yedi modülün tüm becerilerini az yönlendirmeli tek senaryoda bütünleştirmek.",
    skills: ["Bütünleşik klinik karar", "Dinamik yeniden değerlendirme", "Resüsitasyon", "Ekip liderliği", "Devir teslim"],
    horizontalIntegration: ["Acil Tıp", "Kardiyoloji", "Farmakoloji", "Radyoloji", "Anesteziyoloji", "İletişim"],
    verticalIntegration: ["Temel bilim", "Klinik beceri", "Staj", "İntörnlük", "Mezuniyet yeterliliği"],
    initialPhase: "integrated",
    initialVitals: baseVitals,
    requiresRationale: true,
    briefing:
      "Yönlendirme minimumdur. Hastayı kabul et, veriyi topla, problem oluştur, test ve tedaviyi seç. Kateter transferi hazırlanırken beklenmeyen ritim değişikliğini ve ekibi yönet.",
    patientStatement: "Lütfen yardım edin… göğsüm çok ağrıyor.",
    expertApproach:
      "İlk bakı–monitör–EKG eşzamanlı yürütülür; tipik STEMI hızla tanınır, aspirin ve hipoksemiye oksijen verilir, reperfüzyon yolu açılır. VF geliştiğinde CPR ve defibrilasyon gecikmez; lider ekip görevlerini kapalı döngüyle dağıtır ve ROSC sonrası güvenli devir teslim yapar.",
    nextFocus: "Tek tek doğru işlemlerden çok, paralel yürütme, yeniden değerlendirme ve ekip koordinasyonunun toplam akışını iyileştir.",
    actions: [
      {
        id: "integrated-assess",
        label: "İlk bakı–ABCDE, vital ve monitörizasyonu paralel başlat",
        shortLabel: "İlk değerlendirme",
        group: "Hasta kabulü",
        description: "Yüksek riskli hastayı güvenli alana ve sürekli izleme altına alır.",
        rationale: "Tanı süreci ile fizyolojik stabilizasyon eşzamanlı yürütülmelidir.",
        feedback: "Hipoksemi, hipotansiyon ve taşikardi erken tanındı.",
        timeCost: 3,
        score: 14,
        required: true,
        critical: true,
        phase: "integrated",
        safety: "positive",
        skill: "Bütünleşik ilk yaklaşım",
      },
      {
        id: "integrated-history-exam",
        label: "Odaklı OPQRST/SAMPLE anamnez ve fizik muayene yap",
        shortLabel: "Anamnez + muayene",
        group: "Hasta kabulü",
        description: "Tipik iskemi ve hemodinamik risk örüntüsünü toplar.",
        rationale: "Kritik veriyi kısa sürede problem temsiline dönüştürür.",
        feedback: "Tipik ağrı, risk faktörleri ve zayıf perfüzyon tanındı.",
        timeCost: 4,
        score: 12,
        required: true,
        requires: ["integrated-assess"],
        phase: "integrated",
        safety: "positive",
        skill: "Odaklı değerlendirme",
      },
      {
        id: "integrated-ecg",
        label: "12 derivasyonlu EKG çek ve STEMI'yi önceliklendir",
        shortLabel: "EKG + tanı",
        group: "Tanı",
        description: "V1–V4 ST elevasyonunu zamanında tanır.",
        rationale: "Reperfüzyon kararını açan kritik tetkiktir.",
        feedback: "Anterior STEMI tanındı ve ayırıcı tanı sıralaması güncellendi.",
        timeCost: 3,
        score: 18,
        required: true,
        critical: true,
        requires: ["integrated-assess"],
        phase: "integrated",
        safety: "positive",
        skill: "Tanısal öncelik",
        rhythm: "stemi",
      },
      {
        id: "integrated-treatment",
        label: "Aspirin, hedefli oksijen ve damar yolu uygulamalarını başlat",
        shortLabel: "İlk tedavi",
        group: "Tedavi",
        description: "Endikasyon ve kontrendikasyon kontrollü başlangıç tedavisi.",
        rationale: "Hipoksemiyi düzeltir, antiplatelet tedaviyi başlatır ve güvenli erişim sağlar.",
        feedback: "SpO₂ yükseldi; hasta tedavi ve müdahale erişimine alındı.",
        timeCost: 3,
        score: 16,
        required: true,
        requires: ["integrated-history-exam", "integrated-ecg"],
        phase: "integrated",
        safety: "positive",
        skill: "Tedavi bütünleştirme",
        vitalDelta: { spo2: 6, respiratoryRate: -3 },
      },
      {
        id: "integrated-cath",
        label: "Kateter laboratuvarını aktive et ve ekip görevlerini dağıt",
        shortLabel: "Reperfüzyon + ekip",
        group: "Tedavi",
        description: "Zaman kritik yol ve ekip koordinasyonunu eşzamanlı başlatır.",
        rationale: "Kesin tedavi gecikmesini azaltır ve görevleri görünür kılar.",
        feedback: "Transfer hazırlığı başlarken hasta aniden yanıtsızlaştı; monitörde VF oluştu.",
        timeCost: 2,
        score: 15,
        required: true,
        critical: true,
        requires: ["integrated-treatment"],
        phase: "integrated",
        transitionTo: "vf",
        rhythm: "vf",
        safety: "positive",
        skill: "Dinamik yeniden değerlendirme",
      },
      {
        id: "integrated-cpr",
        label: "VF'yi tanı, kod çağrısı yap ve CPR'a başla",
        shortLabel: "VF + CPR",
        group: "Acil değişiklik",
        description: "Beklenmeyen arresti hızlı tanır ve perfüzyonu başlatır.",
        rationale: "Şoklanabilir arrestte ilk saniyeler hasta sonucunu belirler.",
        feedback: "Resüsitasyon aktive edildi ve kompresyon başladı.",
        timeCost: 1,
        score: 18,
        required: true,
        critical: true,
        phase: "vf",
        safety: "positive",
        skill: "Acil yanıt",
      },
      {
        id: "integrated-defib",
        label: "Kapalı döngü komutla erken defibrilasyon uygula",
        shortLabel: "Defibrilasyon",
        group: "Acil değişiklik",
        description: "Ekip güvenliği ve erken şoku birlikte uygular.",
        rationale: "VF'nin en kritik tedavisidir; iletişim hatası şoku geciktirmemelidir.",
        feedback: "Şok uygulandı ve organize ritim geri döndü.",
        timeCost: 2,
        score: 22,
        required: true,
        critical: true,
        requires: ["integrated-cpr"],
        phase: "vf",
        transitionTo: "rosc",
        rhythm: "rosc",
        safety: "positive",
        skill: "Resüsitasyon liderliği",
      },
      {
        id: "integrated-rosc",
        label: "ROSC sonrası ABCDE, 12 derivasyon EKG ve SBAR devir teslimi yap",
        shortLabel: "ROSC sonrası bakım",
        group: "Sonuç",
        description: "Yeniden değerlendirme ve güvenli bakım geçişi.",
        rationale: "Dolaşım geri dönüşü simülasyonun sonu değil, yeni bir bakım fazıdır.",
        feedback: "Hasta kateter laboratuvarına güvenli ve yapılandırılmış biçimde devredildi.",
        timeCost: 4,
        score: 18,
        required: true,
        critical: true,
        requires: ["integrated-defib"],
        phase: "rosc",
        safety: "positive",
        skill: "ROSC sonrası bakım",
      },
      {
        id: "integrated-nitrate",
        label: "Hipotansiyona rağmen nitrat ver",
        shortLabel: "Kontrendike nitrat",
        group: "Kritik hata",
        description: "Dolaşım bozukluğunu ağırlaştırır.",
        rationale: "TA 94/62 iken nitrat ciddi hipotansiyon riski taşır.",
        feedback: "Kan basıncı düştü ve arrest riski hızlandı.",
        timeCost: 1,
        score: -30,
        critical: true,
        phase: "integrated",
        safety: "critical",
        skill: "Kontrendikasyon",
        vitalDelta: { systolic: -24, diastolic: -12, heartRate: 12 },
      },
      {
        id: "integrated-delay",
        label: "Tüm laboratuvar sonuçları gelene kadar reperfüzyon kararını ertele",
        shortLabel: "Kararı ertele",
        group: "Kritik hata",
        description: "Zaman kritik tedaviyi laboratuvar sonucuna bağlar.",
        rationale: "Tanısal EKG bulunan STEMI'de gecikme miyokard kaybını artırır.",
        feedback: "Hasta kötüleşti ve kritik zaman kaybedildi.",
        timeCost: 25,
        score: -32,
        critical: true,
        phase: "integrated",
        safety: "critical",
        skill: "Zaman yönetimi",
        vitalDelta: { systolic: -15, spo2: -3 },
      },
    ],
  },
];

export const curriculumComposition = {
  ucepCore: 70,
  institutionalAutonomy: 30,
  note:
    "Pilot program mimarisi: %70 UÇEP referanslı çekirdek yeterlilik alanı + %30 kurumun program çıktıları, yerel olguları ve seçmeli derinleşme alanları. Resmî UÇEP eşlemesi değildir; akademik kurul doğrulaması gerekir.",
};

export const competencyLoop = [
  "Gözlemle",
  "Düşün",
  "Karar ver",
  "Uygula",
  "Sonucu gör",
  "Değerlendir",
  "Yeniden dene",
];
